name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir-version: 1.10.x
            otp-version: 23.x
          - elixir-version: 1.11.x
            otp-version: 23.x

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir-version }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp-version }} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --cover
    - name: Report coverage
      if: ${{ success() && matrix.elixir-version == '1.11.x' }}
      run: bash <(curl -s https://codecov.io/bash)

  format_doc:

    name: Format and documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.11.x
        otp-version: 23.x
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Check formatted
      run: mix format --check-formatted
    - name: Generate documentation
      run: mix docs
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: doc
